### ISSUE TITLE
Images may get lost after being edited visually in Joplin.

### ISSUE THREAD

**Issue by h2dcc** [joplin-utils/joplin-blog-template#1]
Orginal image:
`![](:/142970433a904c2aa33d3447aff5df9e)`

Edited visually in Joplin:
`<img src=":/142970433a904c2aa33d3447aff5df9e" alt="4aabb661d6b056257e104529374d71eb.png" width="902" height="550">
`

**Comment by rxliuli** [comment]
Please open an issue in the [joplin-utils](https://github.com/rxliuli/joplin-utils/issues) repository.
